name: Trigger Renovate on App

on:
  workflow_dispatch:
  # Trigger when the Release workflow completes successfully
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v44.2.4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GH_PAT }}
        env:
          LOG_LEVEL: ${{ github.event.inputs.logLevel || 'debug' }}
          RENOVATE_REPOSITORIES:
            "draft-semantic-release-app"
